###############################
# Secuboid configuration file #
###############################

# "en" (English) or "fr" (french) currently supported
lang: en

# Database section: If you don't have access to a database, keep the default
# configuration (save to local file).
# IMPORTANT: Need a complete stop and start after a modification in this
# section.
database:
  # Save to local file (default).
  url: "jdbc:hsqldb:file:{{plugin-path}}/storage/db"
  # Use this url bellow if you have access to a MySQL/MariaDB database
  # (recommended). Change "server" for your server url and "secuboid" for the
  # database name. Keep "jdbc:mariadb" if you have MySQL.
  #url: "jdbc:mariadb://server:3306/secuboid"

  # The database username and password.
  user: secuboid
  password: secuboid

selection:
  default-start-diameter: 3
